# Generated by Django 5.2.7 on 2025-10-15 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50, unique=True, verbose_name='ID объекта')),
                ('object_type', models.CharField(choices=[('olt', 'OLT Станция'), ('splice_box', 'Оптическая муфта'), ('splitter', 'Сплиттер-бокс'), ('switch', 'Коммутатор'), ('ats', 'АТС'), ('building', 'Дом')], max_length=20, verbose_name='Тип объекта')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('lng', models.FloatField(verbose_name='Долгота')),
                ('technology', models.CharField(blank=True, choices=[('gpon', 'GPON'), ('adsl', 'ADSL'), ('ethernet', 'Ethernet')], max_length=20, verbose_name='Технология')),
                ('capacity', models.IntegerField(default=0, verbose_name='Общая емкость')),
                ('free_ports', models.IntegerField(default=0, verbose_name='Свободные порты')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telecom_net.infrastructureobject', verbose_name='Родительский объект')),
            ],
            options={
                'verbose_name': 'Объект инфраструктуры',
                'verbose_name_plural': 'Объекты инфраструктуры',
            },
        ),
        migrations.CreateModel(
            name='CableRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название трассы')),
                ('length', models.IntegerField(verbose_name='Длина (метры)')),
                ('fiber_count', models.IntegerField(default=1, verbose_name='Количество волокон')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='telecom_net.infrastructureobject')),
                ('to_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='telecom_net.infrastructureobject')),
            ],
            options={
                'verbose_name': 'Кабельная трасса',
                'verbose_name_plural': 'Кабельные трассы',
            },
        ),
    ]
