# Generated by Django 5.2.7 on 2025-10-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom_net', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cableroute',
            options={'ordering': ['name'], 'verbose_name': 'Кабельная трасса', 'verbose_name_plural': 'Кабельные трассы'},
        ),
        migrations.AlterModelOptions(
            name='infrastructureobject',
            options={'ordering': ['object_id'], 'verbose_name': 'Объект инфраструктуры', 'verbose_name_plural': 'Объекты инфраструктуры'},
        ),
        migrations.AddField(
            model_name='cableroute',
            name='cable_type',
            field=models.CharField(choices=[('fiber', 'Оптический кабель'), ('copper', 'Медный кабель'), ('hybrid', 'Гибридный кабель')], default='fiber', max_length=20, verbose_name='Тип кабеля'),
        ),
        migrations.AddField(
            model_name='cableroute',
            name='documentation',
            field=models.FileField(blank=True, null=True, upload_to='route_docs/', verbose_name='Документация'),
        ),
        migrations.AddField(
            model_name='cableroute',
            name='installation_notes',
            field=models.TextField(blank=True, verbose_name='Примечания по установке'),
        ),
        migrations.AddField(
            model_name='cableroute',
            name='installed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прокладки'),
        ),
        migrations.AddField(
            model_name='cableroute',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная'),
        ),
        migrations.AddField(
            model_name='cableroute',
            name='route_photo',
            field=models.ImageField(blank=True, null=True, upload_to='route_photos/', verbose_name='Фото трассы'),
        ),
        migrations.AddField(
            model_name='cableroute',
            name='route_type',
            field=models.CharField(choices=[('underground', 'Подземная'), ('aerial', 'Воздушная'), ('indoor', 'Внутренняя')], default='underground', max_length=20, verbose_name='Тип прокладки'),
        ),
        migrations.AddField(
            model_name='cableroute',
            name='technical_specs',
            field=models.TextField(blank=True, verbose_name='Технические характеристики'),
        ),
        migrations.AddField(
            model_name='cableroute',
            name='test_results',
            field=models.TextField(blank=True, verbose_name='Результаты тестирования'),
        ),
        migrations.AddField(
            model_name='cableroute',
            name='tested_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата тестирования'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='diagram',
            field=models.ImageField(blank=True, null=True, upload_to='infrastructure_diagrams/', verbose_name='Схема подключения'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата установки'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего обслуживания'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего обслуживания'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='infrastructure_photos/', verbose_name='Фотография объекта'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('planned', 'Запланированный'), ('inactive', 'Неактивный'), ('maintenance', 'На обслуживании')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='infrastructureobject',
            name='technical_notes',
            field=models.TextField(blank=True, verbose_name='Технические примечания'),
        ),
        migrations.AlterField(
            model_name='cableroute',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Общие примечания'),
        ),
        migrations.AlterField(
            model_name='infrastructureobject',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Общие примечания'),
        ),
        migrations.AlterField(
            model_name='infrastructureobject',
            name='object_type',
            field=models.CharField(choices=[('olt', 'OLT Станция'), ('splice_box', 'Оптическая муфта'), ('splitter', 'Сплиттер-бокс'), ('switch', 'Коммутатор'), ('ats', 'АТС'), ('building', 'Дом'), ('client', 'Клиентская точка')], max_length=20, verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='infrastructureobject',
            name='technology',
            field=models.CharField(blank=True, choices=[('gpon', 'GPON'), ('adsl', 'ADSL'), ('ethernet', 'Ethernet'), ('hybrid', 'Гибридный')], max_length=20, verbose_name='Технология'),
        ),
        migrations.CreateModel(
            name='ObjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлен'), ('maintenance', 'Обслуживание'), ('repaired', 'Ремонт')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='history_photos/', verbose_name='Фото')),
                ('performed_by', models.CharField(max_length=100, verbose_name='Выполнил')),
                ('performed_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выполнения')),
                ('infrastructure_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='telecom_net.infrastructureobject')),
            ],
            options={
                'verbose_name': 'История объекта',
                'verbose_name_plural': 'История объектов',
                'ordering': ['-performed_date'],
            },
        ),
    ]
